### ISSUE TITLE
Demo Warning: Failed prop type: The prop `step.id`

### ISSUE THREAD

**Issue by Northshoot** [americanexpress/react-albus#31] opened 2018-09-14 00:25 UTC
Running demo at http://americanexpress.io/react-albus/ gives warning for animation showcase:

```
Warning: Failed prop type: The prop `step.id` is marked as required in `Steps`, but its value is `null`.
    in Steps (created by Wizard)
    in Wizard (created by Route)
    in Route (created by AddAnimation)
    in div (created by AddAnimation)
    in div (created by AddAnimation)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by AddAnimation)
    in AddAnimation
```

**Comment by crosscompile** [comment] 2018-09-21 16:44
Thanks for reporting!  Answered in #29.

**Comment by asutedja** [comment] 2019-12-11 06:36
Closing this due to being a duplicate of #29

**Closed by asutedja** 2019-12-11 06:36 UTC
