### ISSUE TITLE
Current route step doesn't get rendered correctly

### ISSUE THREAD

**Issue by CentaurWarchief** [americanexpress/react-albus#17] opened 2018-02-07 20:03 UTC
Hey guys — nice project!

I'm wondering if this is an issue on my end, or in yours. 

The problem is: if I navigate forward and reach `/ice-king` (https://oqgkj7wmb.codesandbox.io/ice-king), and hit ^R — **Ice King** step doesn't render, I get redirected back to `/gandalf`

Thoughts? Is that a misuse or misunderstanding?

Thanks!

**Comment by crosscompile** [comment] 2018-02-07 22:31
Thanks @CentaurWarchief!  Looks like it is an issue on our end.

Redirecting back to the first step was unintended behavior in v1.x.x but was fixed in v2.0.0.  It looks like we did not update the codesandbox demos to use v2.0.0 so I have done that now.  You should be seeing the behavior you expect at: https://oqgkj7wmb.codesandbox.io.

I'll also move the demo code into the repo so that we can track changes with the rest of the project.

**Closed** 2018-02-08 17:08 UTC
